// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ConversationChannelController from "./conversation_channel_controller"
application.register("conversation-channel", ConversationChannelController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import TypingIndicatorController from "./typing_indicator_controller"
application.register("typing-indicator", TypingIndicatorController)

import DebugOverlayController from "./debug_overlay_controller"
application.register("debug-overlay", DebugOverlayController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import DetailsDropdownController from "./details_dropdown_controller"
application.register("details-dropdown", DetailsDropdownController)

import SectionToggleController from "./section_toggle_controller"
application.register("section-toggle", SectionToggleController)

import ConversationSearchController from "./conversation_search_controller"
application.register("conversation-search", ConversationSearchController)
