# V1: reason_code 常量表
#
# 这些常量需要与 docs/protocol/missionspec_capabilities_net.schema.v1.json 的 enum 保持一致。
# 约定：
# - decision reason_code 用于代理/Nexus 侧审计”为什么放行/拦截”
# - approval reason_code 用于控制面解释“为什么需要审批”

module Conduits
  module NetDecisionReasonCodeV1
    OK               = "OK"
    NET_MODE_NONE    = "NET_MODE_NONE"
    NOT_IN_ALLOWLIST = "NOT_IN_ALLOWLIST"
    PORT_NOT_ALLOWED = "PORT_NOT_ALLOWED"
    INVALID_DESTINATION = "INVALID_DESTINATION"
    PROXY_REQUIRED   = "PROXY_REQUIRED"
    SNI_MISMATCH     = "SNI_MISMATCH"
    DNS_DENIED       = "DNS_DENIED"
    POLICY_EXPIRED   = "POLICY_EXPIRED"      # reserved (future)
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"  # reserved (future)
    INTERNAL_ERROR   = "INTERNAL_ERROR"
    OTHER            = "OTHER"

    ALL = [
      OK, NET_MODE_NONE, NOT_IN_ALLOWLIST, PORT_NOT_ALLOWED, INVALID_DESTINATION,
      PROXY_REQUIRED, SNI_MISMATCH, DNS_DENIED, POLICY_EXPIRED, APPROVAL_REQUIRED,
      INTERNAL_ERROR, OTHER,
    ].freeze
  end

  module NetApprovalReasonCodeV1
    NET_UNRESTRICTED_REQUESTED      = "NET_UNRESTRICTED_REQUESTED"
    NET_NON_DEFAULT_PORT_REQUESTED  = "NET_NON_DEFAULT_PORT_REQUESTED"
    NET_WILDCARD_DOMAIN_REQUESTED   = "NET_WILDCARD_DOMAIN_REQUESTED"
    NET_PRIVATE_DESTINATION_REQUESTED = "NET_PRIVATE_DESTINATION_REQUESTED"
    NET_CUSTOM_POLICY_REQUESTED     = "NET_CUSTOM_POLICY_REQUESTED"

    ALL = [
      NET_UNRESTRICTED_REQUESTED,
      NET_NON_DEFAULT_PORT_REQUESTED,
      NET_WILDCARD_DOMAIN_REQUESTED,
      NET_PRIVATE_DESTINATION_REQUESTED,
      NET_CUSTOM_POLICY_REQUESTED,
    ].freeze
  end
end
